networks:
  plc-network-dev:
    driver: bridge

volumes:
  kafka_data_dev:

services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka-dev
    ports:
      - "9092:9092"
      - "9094:9094"
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data_dev:/var/lib/kafka/data
    networks:
      - plc-network-dev

  postgres:
    image: postgres:17
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - plc-network-dev

  simulator-a1:
    build: ./simulator
    container_name: sim_1
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LINE_ID: A1
      KAFKA_TOPIC: plc.data.raw
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - plc-network-dev
      
  simulator-a2:
    build: ./simulator
    container_name: sim_2
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LINE_ID: A2
      KAFKA_TOPIC: plc.data.raw
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - plc-network-dev