[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["plc.data.raw"]
  consumer_group = "telegraf-plc-consumer"
  offset = "newest"

  data_format = "json_v2"

[[inputs.kafka_consumer.json_v2]]
  measurement_name = "plc"
  timestamp_path   = "timestamp"
  timestamp_format = "unix_ms"

[[inputs.kafka_consumer.json_v2.tag]]
  path   = "lineId"
  rename = "line_id"

[[inputs.kafka_consumer.json_v2.object]]
  path = "registers"
  disable_prepend_keys = true

[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket       = "${INFLUXDB_BUCKET}"