[agent]
  debug = true
  quiet = false
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  hostname = ""

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["plc.data.raw"]
  consumer_group = "telegraf-plc-consumer"
  offset = "newest"
  data_format = "json_v2"

  [[inputs.kafka_consumer.json_v2]]
    measurement_name = "plc"
    timestamp_path   = "timestamp"
    timestamp_format = "RFC3339"

    [[inputs.kafka_consumer.json_v2.tag]]
      path = "line"
      rename = "line_id"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "plcName"
      rename = "plc_name"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "deviceType"
      rename = "device_type"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "profile"

    [[inputs.kafka_consumer.json_v2.object]]
      path = "registers"
      disable_prepend_keys = false
      optional = true

    [[inputs.kafka_consumer.json_v2.object]]
      path = "groupSummary"
      disable_prepend_keys = false
      optional = true

[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket       = "${INFLUXDB_BUCKET}"